// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.Events.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Fastly.OpenApiClient.Events
{
    /// <summary>
    /// Builds and executes requests for operations under \events
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Fastly.OpenApiClient.events.item collection</summary>
        /// <param name="position">Alphanumeric string identifying an event.</param>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Events.Item.WithEvent_ItemRequestBuilder"/></returns>
        public global::Soenneker.Fastly.OpenApiClient.Events.Item.WithEvent_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("event_id", position);
                return new global::Soenneker.Fastly.OpenApiClient.Events.Item.WithEvent_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events{?filter%5Bcreated_at%5D*,filter%5Bcreated_at%5D%5Bgt%5D*,filter%5Bcreated_at%5D%5Bgte%5D*,filter%5Bcreated_at%5D%5Blt%5D*,filter%5Bcreated_at%5D%5Blte%5D*,filter%5Bcustomer_id%5D*,filter%5Bevent_type%5D*,filter%5Bservice_id%5D*,filter%5Btoken_id%5D*,filter%5Buser_id%5D*,page%5Bnumber%5D*,page%5Bsize%5D*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/events{?filter%5Bcreated_at%5D*,filter%5Bcreated_at%5D%5Bgt%5D*,filter%5Bcreated_at%5D%5Bgte%5D*,filter%5Bcreated_at%5D%5Blt%5D*,filter%5Bcreated_at%5D%5Blte%5D*,filter%5Bcustomer_id%5D*,filter%5Bevent_type%5D*,filter%5Bservice_id%5D*,filter%5Btoken_id%5D*,filter%5Buser_id%5D*,page%5Bnumber%5D*,page%5Bsize%5D*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;List all events for a particular customer. Events can be filtered by user, customer and event type. Events can be sorted by date.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Events.EventsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Fastly.OpenApiClient.Events.EventsGetResponse?> GetAsEventsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Fastly.OpenApiClient.Events.EventsGetResponse> GetAsEventsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Fastly.OpenApiClient.Events.EventsGetResponse>(requestInfo, global::Soenneker.Fastly.OpenApiClient.Events.EventsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;List all events for a particular customer. Events can be filtered by user, customer and event type. Events can be sorted by date.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Events.EventsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsEventsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Fastly.OpenApiClient.Events.EventsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Fastly.OpenApiClient.Events.EventsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Fastly.OpenApiClient.Events.EventsResponse>(requestInfo, global::Soenneker.Fastly.OpenApiClient.Events.EventsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;List all events for a particular customer. Events can be filtered by user, customer and event type. Events can be sorted by date.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;List all events for a particular customer. Events can be filtered by user, customer and event type. Events can be sorted by date.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderGetQueryParameters 
        {
            /// <summary>&quot;Limit the returned events to a specific time frame. Accepts sub-parameters: lt, lte, gt, gte (e.g., filter[created_at][gt]=2022-01-12).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bcreated_at%5D")]
            public string? FiltercreatedAt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bcreated_at%5D")]
            public string FiltercreatedAt { get; set; }
#endif
            /// <summary>Return events after a date and time in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bcreated_at%5D%5Bgt%5D")]
            public string? FiltercreatedAtgt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bcreated_at%5D%5Bgt%5D")]
            public string FiltercreatedAtgt { get; set; }
#endif
            /// <summary>Return events on and after a date and time in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bcreated_at%5D%5Bgte%5D")]
            public string? FiltercreatedAtgte { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bcreated_at%5D%5Bgte%5D")]
            public string FiltercreatedAtgte { get; set; }
#endif
            /// <summary>Return events before a date and time in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bcreated_at%5D%5Blt%5D")]
            public string? FiltercreatedAtlt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bcreated_at%5D%5Blt%5D")]
            public string FiltercreatedAtlt { get; set; }
#endif
            /// <summary>Return events on and before a date and time in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bcreated_at%5D%5Blte%5D")]
            public string? FiltercreatedAtlte { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bcreated_at%5D%5Blte%5D")]
            public string FiltercreatedAtlte { get; set; }
#endif
            /// <summary>Limit the results returned to a specific customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bcustomer_id%5D")]
            public string? FiltercustomerId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bcustomer_id%5D")]
            public string FiltercustomerId { get; set; }
#endif
            /// <summary>Limit the returned events to a specific event_type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bevent_type%5D")]
            public string? FiltereventType { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bevent_type%5D")]
            public string FiltereventType { get; set; }
#endif
            /// <summary>Limit the results returned to a specific service.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bservice_id%5D")]
            public string? FilterserviceId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bservice_id%5D")]
            public string FilterserviceId { get; set; }
#endif
            /// <summary>Limit the returned events to a specific token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Btoken_id%5D")]
            public string? FiltertokenId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Btoken_id%5D")]
            public string FiltertokenId { get; set; }
#endif
            /// <summary>Limit the results returned to a specific user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Buser_id%5D")]
            public string? FilteruserId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Buser_id%5D")]
            public string FilteruserId { get; set; }
#endif
            /// <summary>Current page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bnumber%5D")]
            public string? Pagenumber { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bnumber%5D")]
            public string Pagenumber { get; set; }
#endif
            /// <summary>Number of records per page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bsize%5D")]
            public string? Pagesize { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bsize%5D")]
            public string Pagesize { get; set; }
#endif
            /// <summary>The order in which to list the results by creation date.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Events.EventsRequestBuilder.EventsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
