// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \metrics\bots\entities\{serviceId}\{granularity}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGranularityItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGranularityItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics/bots/entities/{serviceId}/{granularity}{?bot*,cursor*,datacenter*,from*,group_by*,limit*,metric*,metric_set*,region*,to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGranularityItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/metrics/bots/entities/{serviceId}/{granularity}{?bot*,cursor*,datacenter*,from*,group_by*,limit*,metric*,metric_set*,region*,to*}", rawUrl)
        {
        }
        /// <summary>
        /// Return historical time series metrics for bot requests broken down by bot-type.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.GetPerServiceHistoricalTimeSeriesMetricsForBotRequestsBrokenDownByBotType200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Fastly.OpenApiClient.Models.GetPerServiceHistoricalTimeSeriesMetricsForBotRequestsBrokenDownByBotType200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder.WithGranularityItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Fastly.OpenApiClient.Models.GetPerServiceHistoricalTimeSeriesMetricsForBotRequestsBrokenDownByBotType200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder.WithGranularityItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Fastly.OpenApiClient.Models.GetPerServiceHistoricalTimeSeriesMetricsForBotRequestsBrokenDownByBotType200Response>(requestInfo, global::Soenneker.Fastly.OpenApiClient.Models.GetPerServiceHistoricalTimeSeriesMetricsForBotRequestsBrokenDownByBotType200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Return historical time series metrics for bot requests broken down by bot-type.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder.WithGranularityItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder.WithGranularityItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Fastly.OpenApiClient.Metrics.Bots.Entities.Item.Item.WithGranularityItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Return historical time series metrics for bot requests broken down by bot-type.&gt; **Authorization**: Requires [API token](/reference/api/auth-tokens).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithGranularityItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter results based by Bot ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("bot")]
            public string? Bot { get; set; }
#nullable restore
#else
            [QueryParameter("bot")]
            public string Bot { get; set; }
#endif
            /// <summary>Cursor value from the next_cursor field of a previous response, used to retrieve the next page. To request the first page, this should be empty.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Limit query to one or more specific POPs. Values should be comma-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("datacenter")]
            public string? Datacenter { get; set; }
#nullable restore
#else
            [QueryParameter("datacenter")]
            public string Datacenter { get; set; }
#endif
            /// <summary>A valid RFC-8339-formatted date and time indicating the inclusive start of the query time range. If not provided, a default is chosen based on the provided granularity value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("from")]
            public string? From { get; set; }
#nullable restore
#else
            [QueryParameter("from")]
            public string From { get; set; }
#endif
            /// <summary>Field to group by in the query.For example, group_by=bot_id will return entries grouped by timestamp and bot_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("group_by")]
            public string? GroupBy { get; set; }
#nullable restore
#else
            [QueryParameter("group_by")]
            public string GroupBy { get; set; }
#endif
            /// <summary>Number of results per page. The maximum is 10000.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("limit")]
            public string? Limit { get; set; }
#nullable restore
#else
            [QueryParameter("limit")]
            public string Limit { get; set; }
#endif
            /// <summary>The metric(s) to retrieve. Multiple values should be comma-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("metric")]
            public string? Metric { get; set; }
#nullable restore
#else
            [QueryParameter("metric")]
            public string Metric { get; set; }
#endif
            /// <summary>The metric set to retrieve.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("metric_set")]
            public string? MetricSet { get; set; }
#nullable restore
#else
            [QueryParameter("metric_set")]
            public string MetricSet { get; set; }
#endif
            /// <summary>Limit query to one or more specific geographic regions. Values should be comma-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("region")]
            public string? Region { get; set; }
#nullable restore
#else
            [QueryParameter("region")]
            public string Region { get; set; }
#endif
            /// <summary>A valid RFC-8339-formatted date and time indicating the exclusive end of the query time range. If not provided, a default is chosen based on the provided granularity value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("to")]
            public string? To { get; set; }
#nullable restore
#else
            [QueryParameter("to")]
            public string To { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
