// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.DdosProtection.V1.Events.Item.Rules.Item.TrafficStats;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fastly.OpenApiClient.DdosProtection.V1.Events.Item.Rules.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \ddos-protection\v1\events\{eventId}\rules\{ruleId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithRuleItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The trafficStats property</summary>
        public global::Soenneker.Fastly.OpenApiClient.DdosProtection.V1.Events.Item.Rules.Item.TrafficStats.TrafficStatsRequestBuilder TrafficStats
        {
            get => new global::Soenneker.Fastly.OpenApiClient.DdosProtection.V1.Events.Item.Rules.Item.TrafficStats.TrafficStatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.DdosProtection.V1.Events.Item.Rules.Item.WithRuleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRuleItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ddos-protection/v1/events/{eventId}/rules/{ruleId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.DdosProtection.V1.Events.Item.Rules.Item.WithRuleItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithRuleItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ddos-protection/v1/events/{eventId}/rules/{ruleId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
