// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Settings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SettingsGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The generalDefault_host property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeneralDefaultHost { get; set; }
#nullable restore
#else
        public string GeneralDefaultHost { get; set; }
#endif
        /// <summary>The generalDefault_ttl property</summary>
        public int? GeneralDefaultTtl { get; set; }
        /// <summary>The generalStale_if_error property</summary>
        public bool? GeneralStaleIfError { get; set; }
        /// <summary>The generalStale_if_error_ttl property</summary>
        public int? GeneralStaleIfErrorTtl { get; set; }
        /// <summary>The service_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceId { get; set; }
#nullable restore
#else
        public string ServiceId { get; set; }
#endif
        /// <summary>The version property</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Settings.SettingsGetResponse"/> and sets the default values.
        /// </summary>
        public SettingsGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Settings.SettingsGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Settings.SettingsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Settings.SettingsGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "general.default_host", n => { GeneralDefaultHost = n.GetStringValue(); } },
                { "general.default_ttl", n => { GeneralDefaultTtl = n.GetIntValue(); } },
                { "general.stale_if_error", n => { GeneralStaleIfError = n.GetBoolValue(); } },
                { "general.stale_if_error_ttl", n => { GeneralStaleIfErrorTtl = n.GetIntValue(); } },
                { "service_id", n => { ServiceId = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("general.default_host", GeneralDefaultHost);
            writer.WriteIntValue("general.default_ttl", GeneralDefaultTtl);
            writer.WriteBoolValue("general.stale_if_error", GeneralStaleIfError);
            writer.WriteIntValue("general.stale_if_error_ttl", GeneralStaleIfErrorTtl);
            writer.WriteStringValue("service_id", ServiceId);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
