// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.Observability.Service.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fastly.OpenApiClient.Observability.Service
{
    /// <summary>
    /// Builds and executes requests for operations under \observability\service
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ServiceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Fastly.OpenApiClient.observability.service.item collection</summary>
        /// <param name="position">Alphanumeric string identifying the service.</param>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Observability.Service.Item.WithServiceItemRequestBuilder"/></returns>
        public global::Soenneker.Fastly.OpenApiClient.Observability.Service.Item.WithServiceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("serviceId", position);
                return new global::Soenneker.Fastly.OpenApiClient.Observability.Service.Item.WithServiceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Observability.Service.ServiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServiceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/observability/service", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Observability.Service.ServiceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ServiceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/observability/service", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
