// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RulesGetResponse_data_rate_limit : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The client_identifiers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit_client_identifiers>? ClientIdentifiers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit_client_identifiers> ClientIdentifiers { get; set; }
#endif
        /// <summary>The duration property</summary>
        public int? Duration { get; set; }
        /// <summary>The interval property</summary>
        public int? Interval { get; set; }
        /// <summary>The threshold property</summary>
        public int? Threshold { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit"/> and sets the default values.
        /// </summary>
        public RulesGetResponse_data_rate_limit()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "client_identifiers", n => { ClientIdentifiers = n.GetCollectionOfObjectValues<global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit_client_identifiers>(global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit_client_identifiers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "interval", n => { Interval = n.GetIntValue(); } },
                { "threshold", n => { Threshold = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Fastly.OpenApiClient.Security.Workspaces.Item.Rules.RulesGetResponse_data_rate_limit_client_identifiers>("client_identifiers", ClientIdentifiers);
            writer.WriteIntValue("duration", Duration);
            writer.WriteIntValue("interval", Interval);
            writer.WriteIntValue("threshold", Threshold);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
