// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Header
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Header : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache_condition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CacheCondition { get; set; }
#nullable restore
#else
        public string CacheCondition { get; set; }
#endif
        /// <summary>The dst property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Dst { get; set; }
#nullable restore
#else
        public string Dst { get; set; }
#endif
        /// <summary>The ignore_if_set property</summary>
        public int? IgnoreIfSet { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The regex property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Regex { get; set; }
#nullable restore
#else
        public string Regex { get; set; }
#endif
        /// <summary>The request_condition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestCondition { get; set; }
#nullable restore
#else
        public string RequestCondition { get; set; }
#endif
        /// <summary>The response_condition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponseCondition { get; set; }
#nullable restore
#else
        public string ResponseCondition { get; set; }
#endif
        /// <summary>The service_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceId { get; set; }
#nullable restore
#else
        public string ServiceId { get; set; }
#endif
        /// <summary>The src property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Src { get; set; }
#nullable restore
#else
        public string Src { get; set; }
#endif
        /// <summary>The substitution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Substitution { get; set; }
#nullable restore
#else
        public string Substitution { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The version property</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Header.Header"/> and sets the default values.
        /// </summary>
        public Header()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Header.Header"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Header.Header CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Header.Header();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "cache_condition", n => { CacheCondition = n.GetStringValue(); } },
                { "dst", n => { Dst = n.GetStringValue(); } },
                { "ignore_if_set", n => { IgnoreIfSet = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "regex", n => { Regex = n.GetStringValue(); } },
                { "request_condition", n => { RequestCondition = n.GetStringValue(); } },
                { "response_condition", n => { ResponseCondition = n.GetStringValue(); } },
                { "service_id", n => { ServiceId = n.GetStringValue(); } },
                { "src", n => { Src = n.GetStringValue(); } },
                { "substitution", n => { Substitution = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("cache_condition", CacheCondition);
            writer.WriteStringValue("dst", Dst);
            writer.WriteIntValue("ignore_if_set", IgnoreIfSet);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("priority", Priority);
            writer.WriteStringValue("regex", Regex);
            writer.WriteStringValue("request_condition", RequestCondition);
            writer.WriteStringValue("response_condition", ResponseCondition);
            writer.WriteStringValue("service_id", ServiceId);
            writer.WriteStringValue("src", Src);
            writer.WriteStringValue("substitution", Substitution);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
