// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.EnabledProducts.V1.Brotli_compression.Services;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fastly.OpenApiClient.EnabledProducts.V1.Brotli_compression
{
    /// <summary>
    /// Builds and executes requests for operations under \enabled-products\v1\brotli_compression
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Brotli_compressionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The services property</summary>
        public global::Soenneker.Fastly.OpenApiClient.EnabledProducts.V1.Brotli_compression.Services.ServicesRequestBuilder Services
        {
            get => new global::Soenneker.Fastly.OpenApiClient.EnabledProducts.V1.Brotli_compression.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.EnabledProducts.V1.Brotli_compression.Brotli_compressionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Brotli_compressionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enabled-products/v1/brotli_compression", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.EnabledProducts.V1.Brotli_compression.Brotli_compressionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Brotli_compressionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enabled-products/v1/brotli_compression", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
