// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAtlsConfiguration201ResponseDataRelationships : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The default_certificate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultCertificate? DefaultCertificate { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultCertificate DefaultCertificate { get; set; }
#endif
        /// <summary>The default_ecdsa_certificate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultEcdsaCertificate? DefaultEcdsaCertificate { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultEcdsaCertificate DefaultEcdsaCertificate { get; set; }
#endif
        /// <summary>The service property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsService? Service { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsService Service { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationships"/> and sets the default values.
        /// </summary>
        public CreateAtlsConfiguration201ResponseDataRelationships()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_certificate", n => { DefaultCertificate = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultCertificate>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultCertificate.CreateFromDiscriminatorValue); } },
                { "default_ecdsa_certificate", n => { DefaultEcdsaCertificate = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultEcdsaCertificate>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultEcdsaCertificate.CreateFromDiscriminatorValue); } },
                { "service", n => { Service = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsService>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsService.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultCertificate>("default_certificate", DefaultCertificate);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsDefaultEcdsaCertificate>("default_ecdsa_certificate", DefaultEcdsaCertificate);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsConfiguration201ResponseDataRelationshipsService>("service", Service);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
