// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateARequestSettingsObject200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bypass_busy_wait property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BypassBusyWait { get; set; }
#nullable restore
#else
        public string BypassBusyWait { get; set; }
#endif
        /// <summary>The default_host property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DefaultHost { get; set; }
#nullable restore
#else
        public UntypedNode DefaultHost { get; set; }
#endif
        /// <summary>The force_miss property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForceMiss { get; set; }
#nullable restore
#else
        public string ForceMiss { get; set; }
#endif
        /// <summary>The force_ssl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ForceSsl { get; set; }
#nullable restore
#else
        public string ForceSsl { get; set; }
#endif
        /// <summary>The geo_headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeoHeaders { get; set; }
#nullable restore
#else
        public string GeoHeaders { get; set; }
#endif
        /// <summary>The hash_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? HashKeys { get; set; }
#nullable restore
#else
        public UntypedNode HashKeys { get; set; }
#endif
        /// <summary>The max_stale_age property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxStaleAge { get; set; }
#nullable restore
#else
        public string MaxStaleAge { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The request_condition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestCondition { get; set; }
#nullable restore
#else
        public string RequestCondition { get; set; }
#endif
        /// <summary>The service_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceId { get; set; }
#nullable restore
#else
        public string ServiceId { get; set; }
#endif
        /// <summary>The timer_support property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimerSupport { get; set; }
#nullable restore
#else
        public string TimerSupport { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>The xff property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Xff { get; set; }
#nullable restore
#else
        public string Xff { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateARequestSettingsObject200Response"/> and sets the default values.
        /// </summary>
        public CreateARequestSettingsObject200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateARequestSettingsObject200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Models.CreateARequestSettingsObject200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Models.CreateARequestSettingsObject200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "bypass_busy_wait", n => { BypassBusyWait = n.GetStringValue(); } },
                { "default_host", n => { DefaultHost = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "force_miss", n => { ForceMiss = n.GetStringValue(); } },
                { "force_ssl", n => { ForceSsl = n.GetStringValue(); } },
                { "geo_headers", n => { GeoHeaders = n.GetStringValue(); } },
                { "hash_keys", n => { HashKeys = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "max_stale_age", n => { MaxStaleAge = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "request_condition", n => { RequestCondition = n.GetStringValue(); } },
                { "service_id", n => { ServiceId = n.GetStringValue(); } },
                { "timer_support", n => { TimerSupport = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
                { "xff", n => { Xff = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("bypass_busy_wait", BypassBusyWait);
            writer.WriteObjectValue<UntypedNode>("default_host", DefaultHost);
            writer.WriteStringValue("force_miss", ForceMiss);
            writer.WriteStringValue("force_ssl", ForceSsl);
            writer.WriteStringValue("geo_headers", GeoHeaders);
            writer.WriteObjectValue<UntypedNode>("hash_keys", HashKeys);
            writer.WriteStringValue("max_stale_age", MaxStaleAge);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("request_condition", RequestCondition);
            writer.WriteStringValue("service_id", ServiceId);
            writer.WriteStringValue("timer_support", TimerSupport);
            writer.WriteStringValue("version", Version);
            writer.WriteStringValue("xff", Xff);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
