// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAtlsSubscription201ResponseDataRelationships : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The common_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsCommonName? CommonName { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsCommonName CommonName { get; set; }
#endif
        /// <summary>The tls_authorizations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsAuthorizations? TlsAuthorizations { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsAuthorizations TlsAuthorizations { get; set; }
#endif
        /// <summary>The tls_certificates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsCertificates? TlsCertificates { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsCertificates TlsCertificates { get; set; }
#endif
        /// <summary>The tls_configuration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsConfiguration? TlsConfiguration { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsConfiguration TlsConfiguration { get; set; }
#endif
        /// <summary>The tls_domains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsDomains? TlsDomains { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsDomains TlsDomains { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationships"/> and sets the default values.
        /// </summary>
        public CreateAtlsSubscription201ResponseDataRelationships()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "common_name", n => { CommonName = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsCommonName>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsCommonName.CreateFromDiscriminatorValue); } },
                { "tls_authorizations", n => { TlsAuthorizations = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsAuthorizations>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsAuthorizations.CreateFromDiscriminatorValue); } },
                { "tls_certificates", n => { TlsCertificates = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsCertificates>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsCertificates.CreateFromDiscriminatorValue); } },
                { "tls_configuration", n => { TlsConfiguration = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsConfiguration>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsConfiguration.CreateFromDiscriminatorValue); } },
                { "tls_domains", n => { TlsDomains = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsDomains>(global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsDomains.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsCommonName>("common_name", CommonName);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsAuthorizations>("tls_authorizations", TlsAuthorizations);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsCertificates>("tls_certificates", TlsCertificates);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsConfiguration>("tls_configuration", TlsConfiguration);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Models.CreateAtlsSubscription201ResponseDataRelationshipsTlsDomains>("tls_domains", TlsDomains);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
