// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RetrieveObservabilityDataAsATimeSeries200ResponseDataItemValues : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avgResponse_time property</summary>
        public double? AvgResponseTime { get; set; }
        /// <summary>The p99Response_time property</summary>
        public double? P99ResponseTime { get; set; }
        /// <summary>The sumScope2_market_mtco2e property</summary>
        public double? SumScope2MarketMtco2e { get; set; }
        /// <summary>The sumScope3_market_mtco2e property</summary>
        public double? SumScope3MarketMtco2e { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Models.RetrieveObservabilityDataAsATimeSeries200ResponseDataItemValues"/> and sets the default values.
        /// </summary>
        public RetrieveObservabilityDataAsATimeSeries200ResponseDataItemValues()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.RetrieveObservabilityDataAsATimeSeries200ResponseDataItemValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Models.RetrieveObservabilityDataAsATimeSeries200ResponseDataItemValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Models.RetrieveObservabilityDataAsATimeSeries200ResponseDataItemValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avg[response_time]", n => { AvgResponseTime = n.GetDoubleValue(); } },
                { "p99[response_time]", n => { P99ResponseTime = n.GetDoubleValue(); } },
                { "sum[scope2_market_mtco2e]", n => { SumScope2MarketMtco2e = n.GetDoubleValue(); } },
                { "sum[scope3_market_mtco2e]", n => { SumScope3MarketMtco2e = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("avg[response_time]", AvgResponseTime);
            writer.WriteDoubleValue("p99[response_time]", P99ResponseTime);
            writer.WriteDoubleValue("sum[scope2_market_mtco2e]", SumScope2MarketMtco2e);
            writer.WriteDoubleValue("sum[scope3_market_mtco2e]", SumScope3MarketMtco2e);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
