// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTls_subscription_PatchRequestBody_data_relationships : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The common_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_common_name? CommonName { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_common_name CommonName { get; set; }
#endif
        /// <summary>The tls_configuration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_configuration? TlsConfiguration { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_configuration TlsConfiguration { get; set; }
#endif
        /// <summary>The tls_domains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_domains? TlsDomains { get; set; }
#nullable restore
#else
        public global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_domains TlsDomains { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships"/> and sets the default values.
        /// </summary>
        public WithTls_subscription_PatchRequestBody_data_relationships()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "common_name", n => { CommonName = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_common_name>(global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_common_name.CreateFromDiscriminatorValue); } },
                { "tls_configuration", n => { TlsConfiguration = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_configuration>(global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_configuration.CreateFromDiscriminatorValue); } },
                { "tls_domains", n => { TlsDomains = n.GetObjectValue<global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_domains>(global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_domains.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_common_name>("common_name", CommonName);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_configuration>("tls_configuration", TlsConfiguration);
            writer.WriteObjectValue<global::Soenneker.Fastly.OpenApiClient.Tls.Subscriptions.Item.WithTls_subscription_PatchRequestBody_data_relationships_tls_domains>("tls_domains", TlsDomains);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
