// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry
{
    /// <summary>
    /// Builds and executes requests for operations under \resources\acls\{acl_id}\entry
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Fastly.OpenApiClient.resources.acls.item.entry.item collection</summary>
        /// <param name="position">valid IPv4 or IPv6 address.</param>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry.Item.WithAcl_ipItemRequestBuilder"/></returns>
        public global::Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry.Item.WithAcl_ipItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("acl_ip", position);
                return new global::Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry.Item.WithAcl_ipItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry.EntryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources/acls/{acl_id}/entry", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Resources.Acls.Item.Entry.EntryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/resources/acls/{acl_id}/entry", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
