// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.Notifications.IntegrationTypes;
using Soenneker.Fastly.OpenApiClient.Notifications.Integrations;
using Soenneker.Fastly.OpenApiClient.Notifications.MailinglistConfirmations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fastly.OpenApiClient.Notifications
{
    /// <summary>
    /// Builds and executes requests for operations under \notifications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotificationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The integrations property</summary>
        public global::Soenneker.Fastly.OpenApiClient.Notifications.Integrations.IntegrationsRequestBuilder Integrations
        {
            get => new global::Soenneker.Fastly.OpenApiClient.Notifications.Integrations.IntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The integrationTypes property</summary>
        public global::Soenneker.Fastly.OpenApiClient.Notifications.IntegrationTypes.IntegrationTypesRequestBuilder IntegrationTypes
        {
            get => new global::Soenneker.Fastly.OpenApiClient.Notifications.IntegrationTypes.IntegrationTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mailinglistConfirmations property</summary>
        public global::Soenneker.Fastly.OpenApiClient.Notifications.MailinglistConfirmations.MailinglistConfirmationsRequestBuilder MailinglistConfirmations
        {
            get => new global::Soenneker.Fastly.OpenApiClient.Notifications.MailinglistConfirmations.MailinglistConfirmationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Notifications.NotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotificationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/notifications", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Notifications.NotificationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotificationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/notifications", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
