// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.V1.Channel.Item.Ts;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Fastly.OpenApiClient.V1.Channel.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\channel\{service_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithService_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ts property</summary>
        public global::Soenneker.Fastly.OpenApiClient.V1.Channel.Item.Ts.TsRequestBuilder Ts
        {
            get => new global::Soenneker.Fastly.OpenApiClient.V1.Channel.Item.Ts.TsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.V1.Channel.Item.WithService_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithService_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/channel/{service_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.V1.Channel.Item.WithService_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithService_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/channel/{service_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
