// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Service.Item.Dictionary.Item.Item_by_id.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithDictionary_item_keyPutResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The deleted_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeletedAt { get; set; }
#nullable restore
#else
        public string DeletedAt { get; set; }
#endif
        /// <summary>The dictionary_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DictionaryId { get; set; }
#nullable restore
#else
        public string DictionaryId { get; set; }
#endif
        /// <summary>The item_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemKey { get; set; }
#nullable restore
#else
        public string ItemKey { get; set; }
#endif
        /// <summary>The item_value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemValue { get; set; }
#nullable restore
#else
        public string ItemValue { get; set; }
#endif
        /// <summary>The service_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceId { get; set; }
#nullable restore
#else
        public string ServiceId { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.Dictionary.Item.Item_by_id.Item.WithDictionary_item_keyPutResponse"/> and sets the default values.
        /// </summary>
        public WithDictionary_item_keyPutResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.Dictionary.Item.Item_by_id.Item.WithDictionary_item_keyPutResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Service.Item.Dictionary.Item.Item_by_id.Item.WithDictionary_item_keyPutResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Service.Item.Dictionary.Item.Item_by_id.Item.WithDictionary_item_keyPutResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deleted_at", n => { DeletedAt = n.GetStringValue(); } },
                { "dictionary_id", n => { DictionaryId = n.GetStringValue(); } },
                { "item_key", n => { ItemKey = n.GetStringValue(); } },
                { "item_value", n => { ItemValue = n.GetStringValue(); } },
                { "service_id", n => { ServiceId = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("deleted_at", DeletedAt);
            writer.WriteStringValue("dictionary_id", DictionaryId);
            writer.WriteStringValue("item_key", ItemKey);
            writer.WriteStringValue("item_value", ItemValue);
            writer.WriteStringValue("service_id", ServiceId);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
