// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Fastly.OpenApiClient.Models;
using Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists
{
    /// <summary>
    /// Builds and executes requests for operations under \network-protect\v1\prefix-lists
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PrefixListsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Fastly.OpenApiClient.networkProtect.v1.prefixLists.item collection</summary>
        /// <param name="position">Unique identifier of the Network Protect prefix list.</param>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.Item.WithPrefixListItemRequestBuilder"/></returns>
        public global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.Item.WithPrefixListItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("prefixListId", position);
                return new global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.Item.WithPrefixListItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrefixListsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/network-protect/v1/prefix-lists{?cursor*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PrefixListsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/network-protect/v1/prefix-lists{?cursor*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists prefix lists in ascending ID order. Positive limits above 1000 are accepted and clamped to 1000. Invalid limits return a 400 Bad Request error.&gt; **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](/guides/organizations-and-accounts/user-and-account-management/about-user-roles-and-permissions&quot;) permissions.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.ListNetworkProtectPrefixLists200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Fastly.OpenApiClient.Models.ListNetworkProtectPrefixLists200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder.PrefixListsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Fastly.OpenApiClient.Models.ListNetworkProtectPrefixLists200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder.PrefixListsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Fastly.OpenApiClient.Models.ListNetworkProtectPrefixLists200Response>(requestInfo, global::Soenneker.Fastly.OpenApiClient.Models.ListNetworkProtectPrefixLists200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a typed list of addresses that rules can reference. The family is required and cannot be changed. The addresses list may remain empty.&gt; **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](/guides/organizations-and-accounts/user-and-account-management/about-user-roles-and-permissions&quot;) permissions.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixList201Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixList201Response?> PostAsync(global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixListRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixList201Response> PostAsync(global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixListRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixList201Response>(requestInfo, global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixList201Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists prefix lists in ascending ID order. Positive limits above 1000 are accepted and clamped to 1000. Invalid limits return a 400 Bad Request error.&gt; **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](/guides/organizations-and-accounts/user-and-account-management/about-user-roles-and-permissions&quot;) permissions.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder.PrefixListsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder.PrefixListsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a typed list of addresses that rules can reference. The family is required and cannot be changed. The addresses list may remain empty.&gt; **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](/guides/organizations-and-accounts/user-and-account-management/about-user-roles-and-permissions&quot;) permissions.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixListRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Fastly.OpenApiClient.Models.CreateANetworkProtectPrefixListRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Fastly.OpenApiClient.NetworkProtect.V1.PrefixLists.PrefixListsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists prefix lists in ascending ID order. Positive limits above 1000 are accepted and clamped to 1000. Invalid limits return a 400 Bad Request error.&gt; **Authorization**: [API token](/reference/api/auth-tokens) with at least [Engineer](/guides/organizations-and-accounts/user-and-account-management/about-user-roles-and-permissions&quot;) permissions.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PrefixListsRequestBuilderGetQueryParameters 
        {
            /// <summary>Continuation value from a previous response&apos;s meta.next_cursor. Omit this parameter to request the first page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Maximum resources to return. Defaults to 100. Positive values above 1000 are accepted and clamped to 1000; the effective value is reported in meta.limit. Zero, negative, and non-integer values return a 400 Bad Request error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("limit")]
            public string? Limit { get; set; }
#nullable restore
#else
            [QueryParameter("limit")]
            public string Limit { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
