// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Logging.Https.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithLogging_https_namePutResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The created_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The deleted_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeletedAt { get; set; }
#nullable restore
#else
        public string DeletedAt { get; set; }
#endif
        /// <summary>The format property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Format { get; set; }
#nullable restore
#else
        public string Format { get; set; }
#endif
        /// <summary>The format_version property</summary>
        public int? FormatVersion { get; set; }
        /// <summary>The header_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderName { get; set; }
#nullable restore
#else
        public string HeaderName { get; set; }
#endif
        /// <summary>The header_value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HeaderValue { get; set; }
#nullable restore
#else
        public string HeaderValue { get; set; }
#endif
        /// <summary>The json_format property</summary>
        public int? JsonFormat { get; set; }
        /// <summary>The message_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageType { get; set; }
#nullable restore
#else
        public string MessageType { get; set; }
#endif
        /// <summary>The method property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Method { get; set; }
#nullable restore
#else
        public string Method { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The period property</summary>
        public int? Period { get; set; }
        /// <summary>The placement property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placement { get; set; }
#nullable restore
#else
        public string Placement { get; set; }
#endif
        /// <summary>The request_max_bytes property</summary>
        public int? RequestMaxBytes { get; set; }
        /// <summary>The request_max_entries property</summary>
        public int? RequestMaxEntries { get; set; }
        /// <summary>The response_condition property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponseCondition { get; set; }
#nullable restore
#else
        public string ResponseCondition { get; set; }
#endif
        /// <summary>The service_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceId { get; set; }
#nullable restore
#else
        public string ServiceId { get; set; }
#endif
        /// <summary>The tls_ca_cert property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsCaCert { get; set; }
#nullable restore
#else
        public string TlsCaCert { get; set; }
#endif
        /// <summary>The tls_client_cert property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsClientCert { get; set; }
#nullable restore
#else
        public string TlsClientCert { get; set; }
#endif
        /// <summary>The tls_client_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsClientKey { get; set; }
#nullable restore
#else
        public string TlsClientKey { get; set; }
#endif
        /// <summary>The tls_hostname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TlsHostname { get; set; }
#nullable restore
#else
        public string TlsHostname { get; set; }
#endif
        /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The version property</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Logging.Https.Item.WithLogging_https_namePutResponse"/> and sets the default values.
        /// </summary>
        public WithLogging_https_namePutResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Logging.Https.Item.WithLogging_https_namePutResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Logging.Https.Item.WithLogging_https_namePutResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Fastly.OpenApiClient.Service.Item.VersionNamespace.Item.Logging.Https.Item.WithLogging_https_namePutResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content_type", n => { ContentType = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deleted_at", n => { DeletedAt = n.GetStringValue(); } },
                { "format", n => { Format = n.GetStringValue(); } },
                { "format_version", n => { FormatVersion = n.GetIntValue(); } },
                { "header_name", n => { HeaderName = n.GetStringValue(); } },
                { "header_value", n => { HeaderValue = n.GetStringValue(); } },
                { "json_format", n => { JsonFormat = n.GetIntValue(); } },
                { "message_type", n => { MessageType = n.GetStringValue(); } },
                { "method", n => { Method = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "period", n => { Period = n.GetIntValue(); } },
                { "placement", n => { Placement = n.GetStringValue(); } },
                { "request_max_bytes", n => { RequestMaxBytes = n.GetIntValue(); } },
                { "request_max_entries", n => { RequestMaxEntries = n.GetIntValue(); } },
                { "response_condition", n => { ResponseCondition = n.GetStringValue(); } },
                { "service_id", n => { ServiceId = n.GetStringValue(); } },
                { "tls_ca_cert", n => { TlsCaCert = n.GetStringValue(); } },
                { "tls_client_cert", n => { TlsClientCert = n.GetStringValue(); } },
                { "tls_client_key", n => { TlsClientKey = n.GetStringValue(); } },
                { "tls_hostname", n => { TlsHostname = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("content_type", ContentType);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("deleted_at", DeletedAt);
            writer.WriteStringValue("format", Format);
            writer.WriteIntValue("format_version", FormatVersion);
            writer.WriteStringValue("header_name", HeaderName);
            writer.WriteStringValue("header_value", HeaderValue);
            writer.WriteIntValue("json_format", JsonFormat);
            writer.WriteStringValue("message_type", MessageType);
            writer.WriteStringValue("method", Method);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("period", Period);
            writer.WriteStringValue("placement", Placement);
            writer.WriteIntValue("request_max_bytes", RequestMaxBytes);
            writer.WriteIntValue("request_max_entries", RequestMaxEntries);
            writer.WriteStringValue("response_condition", ResponseCondition);
            writer.WriteStringValue("service_id", ServiceId);
            writer.WriteStringValue("tls_ca_cert", TlsCaCert);
            writer.WriteStringValue("tls_client_cert", TlsClientCert);
            writer.WriteStringValue("tls_client_key", TlsClientKey);
            writer.WriteStringValue("tls_hostname", TlsHostname);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteStringValue("url", Url);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
